// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://psfxzpnqvojzjxdhztrp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBzZnh6cG5xdm9qemp4ZGh6dHJwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU0MTI2NTUsImV4cCI6MjA3MDk4ODY1NX0.TCJWTJcYz0n2a8LYFiOjmTjjjlx7fbe3NQxn1f98Qnc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});